# Generated by Django 5.2.8 on 2026-04-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='resume/')),
                ('job_desc', models.TextField()),
                ('ats_score', models.FloatField(default=0)),
                ('job_match', models.FloatField(default=0)),
                ('skills_found', models.TextField(default='None')),
                ('missing', models.TextField(default='None')),
                ('job_recommendation', models.TextField(default='Not Available')),
            ],
        ),
    ]
