# Generated by Django 5.2.8 on 2026-04-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resumeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedata',
            name='general_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='ats_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='job_match',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='job_recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='missing',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='skills_found',
            field=models.TextField(blank=True),
        ),
    ]
